### PR TITLE
Docker: python:3-slim-bookworm, Docker Image CI: produce pre-builded docker images

### PR DESCRIPTION
**Pull request by cageyv**
- .dockerignore: exclude files from Docker Image. Make it more secure 
- .github/workflows/docker-image.yml: simple CI. Build container image, push to github registry, sign. Run only for tags: `[ 'v*.*.*' ]`
- Dockerfile:
  - python:3-slim-bookworm: playwright is not supported in alpine. https://github.com/microsoft/playwright-python/issues/1770#issuecomment-1436737822 
  - compile with en_US.UTF-8 default locale for `en` 
  - `COPY requirements.txt requirements.txt` increase building speed by changing order of docker layers 
  - `ENTRYPOINT ["python"]` allows to run cli version of the tool from image and it could be used inside CI/CD systems 
- Makefile: shortcut 
- README.md: info about docker and cli 
- bin/redbot_daemon.py: fallback to default locale in case of config file is missing 

In case of someone looking for pre-builded images: https://github.com/cageyv/redbot/pkgs/container/redbot

### CODE REVIEW

**Comment by cageyv** [comment]
Changes
- Dockerfile: fixed locale issue 

There is another problem, but probably we have to fix it inside thor itself

```
docker run --rm --name redbot -p 8000:8000 redbot
Starting on PID 1... (thor 0.9.6)
http://:8000/
^CStopping...
^C^C^C^C^C^C^C
```

there is high chance that, thor can't handle SIGTERM signal :( 
https://github.com/mnot/thor/blob/3d87d9e18793b987a23dccfa7101171cb1a26f8e/thor/loop.py#L159

```
import signal

def signal_handler(sig, frame):
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGTERM, signal_handler)
```

But I suggest to take a look that issue later, it is not critical

**Comment by cageyv** [comment]
There is another problem, but probably we have to fix it inside thor itself

```
docker run --rm --name redbot -p 8000:8000 redbot
Starting on PID 1... (thor 0.9.6)
http://:8000/
^CStopping...
^C^C^C^C^C^C^C
```

there is high chance that, thor can't handle SIGTERM signal :( 
https://github.com/mnot/thor/blob/3d87d9e18793b987a23dccfa7101171cb1a26f8e/thor/loop.py#L159

```
import signal

def signal_handler(sig, frame):
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGTERM, signal_handler)
```

But I suggest to take a look that issue later, it is not critical

**Comment by mnot** [comment]
This looks good to me -- I'm not a regular Docker user, but appreciate that some folks want to run it that way.

Two things -

1. I just switched over to pipx-based install - see `README.md`.
2. Building on `[push]` is probably too often; as you can probably tell by the history, I'm not terribly disciplined in my pushes :) I'm thinking of changing to [calver](https://calver.org) versioning (probably `YYYY.MM.MINOR`) and doing releases more often on GitHub, so doing it on `[release]` might work better. I'm probably going to start working on this today.

If you don't have time to do these, tell me and I'll just merge and integrate myself. 

Thanks again!

**Comment by cageyv** [comment]
```yml
  push:
    tags: [ 'v*.*.*' ] # Publish semver tags as releases.
```
We will build only in case of specific tag appears. (Inside fork you could see it in actions tab)

`pipx-based install` will do it as is in README. Just give me some time

**Comment by mnot** [comment]
Working on the release stuff now, yep -- tags will do it just fine. Thanks!

**Comment by cageyv** [comment]
I will open the new one :) 
It basically require full redo

**Comment by mnot** [comment]
Sorry.

**Comment by cageyv** [comment]
No worries. Actually it is a good idea with python -m build 
I personally like it 
But it is require more time to use it inside docker and implement multi-stage builds for python 
Looking forward for it

**Pull request closed without merging**
