### PR TITLE
Run tests on Python 3.12

### PR DESCRIPTION
**Pull request by szepeviktor**
https://www.python.org/downloads/ 📅

### CODE REVIEW

**Comment by szepeviktor** [comment]
Reason for failure: https://github.com/python-greenlet/greenlet/issues/365#issuecomment-1694330099

**Comment by mnot** [comment]
Waiting for https://github.com/microsoft/playwright-python/issues/2096

**Comment by szepeviktor** [comment]
Ready 🍏 https://github.com/microsoft/playwright-python/pull/2116

**Comment by szepeviktor** [comment]
Successful launch 🚀

**Pull request merged**
